FROM php:5.6-apache
#RUN apt-get update && apt-get install -y mysql-client php5-mysql 
RUN apt-get update && apt-get install -y php5.6 vim
RUN docker-php-ext-install mysqli
#COPY config/php.ini /usr/local/etc/php/
#COPY /var/www/wordy_dictionary_educator/ /var/www/html/
